name: Run data retrieval

on:
  workflow_dispatch:
  schedule:
    - cron: "*/10 7-21 * * *"
    
jobs:
  gather_and_push:
    runs-on: [ubuntu-latest]

    env:
      BASEURL: ${{ secrets.SES_BASEURL }}
      TOKEN: ${{ secrets.SES_TOKEN }}
      SNID: ${{ secrets.SES_SNID }}

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Gather data
        shell: pwsh
        run: |
          .\gather-stats.ps1

      - name: Commit snapshot
        run: |
          git config user.email github-actions@github.com
          git config user.name github-actions
          git add .
          git commit -m "Update snapshot"
          git push
